### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by parsibox** [MaryamBoneh/Vehicle-Detection#2]
hi
i can not install it
```
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
```

```
 pip install -r requirements.txt
Collecting matplotlib>=3.2.2
  Using cached matplotlib-3.5.1-cp310-cp310-win_amd64.whl (7.2 MB)
Collecting numpy>=1.18.5
  Using cached numpy-1.22.1-cp310-cp310-win_amd64.whl (14.7 MB)
Collecting opencv-python>=4.1.2
  Using cached opencv_python-4.5.5.62-cp36-abi3-win_amd64.whl (35.4 MB)
Collecting Pillow>=8.0.0
  Using cached Pillow-9.0.0-cp310-cp310-win_amd64.whl (3.2 MB)
Collecting PyYAML>=5.3.1
  Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
Collecting scipy>=1.4.1
  Using cached scipy-1.7.3-cp310-cp310-win_amd64.whl (34.3 MB)
ERROR: Could not find a version that satisfies the requirement torch>=1.7.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.7.0
```

**Comment by MaryamBoneh** [comment]
@parsibox  Hi, try it with python 3.9 or 3.8

**Comment by parsibox** [comment]
i change it to Python 3.8.0
run this code 
```
 python train.py --img 640 --batch 16 --epochs 50 --data dataset.yaml --weights yolov5m.pt
train: weights=yolov5m.pt, cfg=, data=dataset.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=50, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, entity=None, name=exp, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1, freeze=0, patience=30
github: skipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
Traceback (most recent call last):
  File "train.py", line 611, in <module>
    main(opt)
  File "train.py", line 487, in main
    opt.data, opt.cfg, opt.hyp = check_file(opt.data), check_file(opt.cfg), check_file(opt.hyp)  # check files
  File "D:\python\test\Vehicle-Detection-main\utils\general.py", line 260, in check_file
    assert len(files), f'File not found: {file}'  # assert file was found
AssertionError: File not found: dataset.yaml
```
this is my downloade dataset folder
![image](https://user-images.githubusercontent.com/12513476/149661500-53ac0645-c5d7-453d-9a37-2dac9a428ebd.png)

**Comment by MaryamBoneh** [comment]
@parsibox You need to create file **dataset.yaml** related to your dataset and place it in the main folder. To use the dataset that I put the link in **readme.md** , you can use [this](https://github.com/MaryamBoneh/Vehicle-Detection#datasetyaml).

**Comment by parsibox** [comment]
thank you deare i get this warnig after creation of dataset.yaml
is it important?
```
:\Python\Python38\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
```

**Comment by MaryamBoneh** [comment]
@parsibox You're welcome.
No it's not. Because you run it on the CPU.
